AWSTemplateFormatVersion: 2010-09-09
Resources:
 DevEC2Instance:
  Type: "AWS::EC2::Instance"
  Properties:
   ImageId: 'ami-0c64dd618a49aeee8' 
   InstanceType: t2.small
   KeyName: cfn-key-2
   SecurityGroups:
    - default
    - Ref: SSHSecurityGroup
 SSHSecurityGroup:
  Type: "AWS::EC2::SecurityGroup"
  Properties:
   GroupDescription: my new SSH
   SecurityGroupIngress:
    - IpProtocol: tcp
      FromPort: '22'
      ToPort: '22'
      CidrIp: 0.0.0.0/0     
    - IpProtocol: tcp
      FromPort: '8080'
      ToPort: '8080'
      CidrIp: 0.0.0.0/0